package org.acgchat.client;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import org.acgchat.common.ChatMessage;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.security.NoSuchAlgorithmException;
import java.security.cert.CertificateException;
import java.util.Date;

/**
 * When the client registers or logins from {@link ClientGUIRegister} and {@link ClientGUILogin} respectively,
 * this class object will be created to be the middleman of the GUI and the backend code.
 * Authors: Kelvin, Darren, QiuRong, Jonathan
 * Class: DISM/FT/2B/02
 */
public class ClientGUI {
    private JPanel mainPanel;
    private JTextField messageTextField;
    private JTextArea messagesTextArea;
    private JButton sendButton;
    private JButton logoutButton;
    private ClientGUIObject clientGUIObject;
    private JFrame init;
    private ClientGUILogin clientGUILogin;
    private String userName;

    /**
     * Initialise the main GUI panel for chatting.
     *
     * @param init           The {@link JFrame} that holds all the JPanels. Used for switching the JPanels.
     * @param clientGUILogin The login panel to redirect back to if an error occurs or the user logs out.
     * @param server         The server's IP or host name
     * @param port           The server's port number
     * @param cacert         The location of the root CA's certificate
     * @param login          Determines if the connection starts as a login (true) or a register (false)
     * @param username       The username to conenct as
     * @param password       The password to authenticate as
     * @throws CertificateException     When the certificate given is invalid
     * @throws IOException              When the file has issues loading
     * @throws NoSuchAlgorithmException When the algorithm for the certificate does not exist
     */
    public ClientGUI(final JFrame init, final ClientGUILogin clientGUILogin, String server, int port, String cacert, boolean login, String username, String password) throws CertificateException, NoSuchAlgorithmException, IOException {
        this.init = init;
        this.clientGUILogin = clientGUILogin;
        this.userName = username;
        clientGUIObject = new ClientGUIObject(server, port, cacert, login, username, password);

        // Set the JFrame to render the ClientGUI.
        init.setContentPane(mainPanel);
        init.setTitle("ACG Chat Client");
        init.pack();

        if (login)
            clientGUIObject.system("Attempting to login...");
        else
            clientGUIObject.system("Attempting to register...");

        // Register the action listener for the logout button
        logoutButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                if (clientGUIObject != null)
                    clientGUIObject.disconnect();

                init.setContentPane(clientGUILogin.getLoginPanel());
                init.setTitle("ACG Chat Client Login");
                init.pack();
            }
        });

        // Start the connection to the server
        if (clientGUIObject.start()) {
            clientGUIObject.system("Connected and logged in!");

            // If connection is successful, start the action listener to handle message sending.
            SendMessageActionListener sendMessageActionListener = new SendMessageActionListener();

            messageTextField.setEnabled(true);
            messageTextField.addActionListener(sendMessageActionListener);
            sendButton.setEnabled(true);
            sendButton.addActionListener(sendMessageActionListener);
        } else {
            clientGUIObject.system("Try logging out and logging back in.");
        }

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(3, 3, new Insets(5, 5, 5, 5), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("Enter Message");
        mainPanel.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        messageTextField = new JTextField();
        messageTextField.setEditable(true);
        messageTextField.setEnabled(false);
        messageTextField.setText("");
        mainPanel.add(messageTextField, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        mainPanel.add(scrollPane1, new GridConstraints(2, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(650, 350), null, 0, false));
        messagesTextArea = new JTextArea();
        messagesTextArea.setEditable(false);
        scrollPane1.setViewportView(messagesTextArea);
        sendButton = new JButton();
        sendButton.setEnabled(false);
        sendButton.setText("Send");
        mainPanel.add(sendButton, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        logoutButton = new JButton();
        logoutButton.setText("Logout");
        mainPanel.add(logoutButton, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

    /**
     * The GUI's implementation of the command line interface version of {@link Client}
     */
    public class ClientGUIObject extends Client {

        /**
         * Initialise the ClientGUIObject with the required variables
         *
         * @param server   The server's IP or host name
         * @param port     The server's port number
         * @param cacert   The location of the root CA's certificate
         * @param login    Determines if the connection starts as a login (true) or a register (false)
         * @param username The username to conenct as
         * @param password The password to authenticate as
         * @throws CertificateException     When the certificate given is invalid
         * @throws IOException              When the file has issues loading
         * @throws NoSuchAlgorithmException When the algorithm for the certificate does not exist
         */
        public ClientGUIObject(String server, int port, String cacert, boolean login, String username, String password) throws CertificateException, IOException, NoSuchAlgorithmException {
            super(server, port, cacert, login, username, password);
        }

        @Override
        public void error(String message) {
            messagesTextArea.append(simpleDateFormat.format(new Date()) + " - SYSTEM: " + message + "\n");
            messagesTextArea.setCaretPosition(messagesTextArea.getText().length() - 1);
            JOptionPane.showConfirmDialog(init, message, "Error", JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
            log("ERROR", message);
        }

        @Override
        public void chat(String message) {
            messagesTextArea.append(simpleDateFormat.format(new Date()) + " - " + message + "\n");
            messagesTextArea.setCaretPosition(messagesTextArea.getText().length() - 1);
        }

        /**
         * Used for system messages to be printed on the GUI
         *
         * @param message The system message to be displayed on the user's GUI textbox.
         */
        public void system(String message) {
            chat("SYSTEM: " + message);
        }
    }

    /**
     * Used for detecting when the enter key is pressed in any text field or the send button is pressed.
     */
    private class SendMessageActionListener implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            String msg = messageTextField.getText();
            // Send a logout message
            if (msg.equalsIgnoreCase("/logout")) {
                clientGUIObject.sendMessage(new ChatMessage(ChatMessage.ChatMessageType.LOGOUT, userName, ""));
            }
            // Send a command
            else if (msg.startsWith("/")) {
                clientGUIObject.sendMessage(new ChatMessage(ChatMessage.ChatMessageType.COMMAND, userName, msg.substring(1)));
            } else {                // default to ordinary message
                clientGUIObject.sendMessage(new ChatMessage(ChatMessage.ChatMessageType.MESSAGE, userName, msg));
            }
            // Clear the message box.
            messageTextField.setText("");
        }
    }

}
